version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0576
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mehediimun@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

  go_app:
    build: .
    container_name: go_app
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  pgdata:
